project:
  type: website
  output-dir: docs

website:
  title: "Jungin Choi"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - analysis.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

